# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loaded_Pl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', jsonfield.fields.JSONField()),
                ('name', models.CharField(max_length=100)),
                ('sha1', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Loaded_Pltp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', jsonfield.fields.JSONField()),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=360)),
                ('sha1', models.CharField(max_length=160)),
            ],
        ),
        migrations.AddField(
            model_name='loaded_pl',
            name='pltp',
            field=models.ManyToManyField(to='gitload.Loaded_Pltp'),
        ),
    ]
