# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitload', '0003_auto_20170517_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repo',
            new_name='Repository',
        ),
    ]
