# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gitload', '0004_auto_20170517_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='PL',
            fields=[
                ('json', jsonfield.fields.JSONField()),
                ('name', models.CharField(max_length=100)),
                ('sha1', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('rel_path', models.CharField(max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='PLTP',
            fields=[
                ('json', jsonfield.fields.JSONField()),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=360)),
                ('sha1', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('rel_path', models.CharField(max_length=360)),
            ],
        ),
        migrations.RemoveField(
            model_name='loaded_pl',
            name='pltp',
        ),
        migrations.AddField(
            model_name='repository',
            name='version',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Loaded_Pl',
        ),
        migrations.DeleteModel(
            name='Loaded_Pltp',
        ),
        migrations.AddField(
            model_name='pltp',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gitload.Repository'),
        ),
        migrations.AddField(
            model_name='pl',
            name='pltp',
            field=models.ManyToManyField(to='gitload.PLTP'),
        ),
        migrations.AddField(
            model_name='pl',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gitload.Repository'),
        ),
    ]
